#!/bin/bash

SELECTED_DIRECTORY=$(find $WORKSPACE $PERSONAL -maxdepth 1 -type d -print | fzf)

if [ -z "$SELECTED_DIRECTORY" ]; then
    echo "Bye!!!"
    exit 1
fi

SESSION_NAME=$(basename $SELECTED_DIRECTORY)

if [[ "$TERM_PROGRAM" == "WezTerm" ]]; then
  wezterm cli spawn --new-window --workspace "$SESSION_NAME" --cwd "$SELECTED_DIRECTORY" zsh
else
  if [[ -n "$TMUX" ]]; then
    # Create a new tmux session with the selected directory as the name and cwd
    tmux new-session -d -s "$SESSION_NAME" -c "$SELECTED_DIRECTORY"

    # Swap to the newly created session
    tmux switch-client -t "$SESSION_NAME"
  else
    # Create a new tmux session with the selected directory as the name and cwd
    tmux new-session -s "$SESSION_NAME" -c "$SELECTED_DIRECTORY"
  fi
fi
